services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gainorloss-backend

    environment:
      NODE_ENV: production
      PORT: 3001
      NEXT_PUBLIC_THEGRAPH_API_KEY: ${NEXT_PUBLIC_THEGRAPH_API_KEY}
      NEXT_PUBLIC_GNOSISSCAN_API_KEY: ${NEXT_PUBLIC_GNOSISSCAN_API_KEY}
      NEXT_PUBLIC_GNOSIS_RPC_URL: ${NEXT_PUBLIC_GNOSIS_RPC_URL:-https://rpc.gnosischain.com/}
      CORS_ORIGIN: https://gainorloss.battistu.com

    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      
      # HTTP → redirection HTTPS
      - "traefik.http.routers.gainorloss-api-http.rule=Host(`api-gainorloss.battistu.com`)"
      - "traefik.http.routers.gainorloss-api-http.entrypoints=web"
      - "traefik.http.routers.gainorloss-api-http.middlewares=redirect-to-https@file"
      
      # HTTPS
      - "traefik.http.routers.gainorloss-api.rule=Host(`api-gainorloss.battistu.com`)"
      - "traefik.http.routers.gainorloss-api.entrypoints=websecure"
      - "traefik.http.routers.gainorloss-api.tls.certresolver=letsencrypt"
      
      # Service interne à exposer
      - "traefik.http.services.gainorloss-api.loadbalancer.server.port=3001"

    networks:
      - traefik
      - internal

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
    container_name: gainorloss-frontend

    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_BACKEND_URL: https://api-gainorloss.battistu.com #TODO change it on realtoken.com
      NEXT_PUBLIC_GNOSISSCAN_API_KEY: ${NEXT_PUBLIC_GNOSISSCAN_API_KEY}
      NEXT_PUBLIC_THEGRAPH_API_URL: ${NEXT_PUBLIC_THEGRAPH_API_URL}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"

      # HTTP → redirection HTTPS
      - "traefik.http.routers.gainorloss-http.rule=Host(`gainorloss.battistu.com`)"
      - "traefik.http.routers.gainorloss-http.entrypoints=web"
      - "traefik.http.routers.gainorloss-http.middlewares=redirect-to-https@file"

      # HTTPS
      - "traefik.http.routers.gainorloss.rule=Host(`gainorloss.battistu.com`)"
      - "traefik.http.routers.gainorloss.entrypoints=websecure"
      - "traefik.http.routers.gainorloss.tls.certresolver=letsencrypt"

      # service interne à exposer
      - "traefik.http.services.gainorloss.loadbalancer.server.port=3000"

    depends_on:
      - backend

    networks:
      - traefik
      - internal

networks:
  traefik:
    external: true
    name: traefik_default

  internal:
    driver: bridge

